# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CustomLabel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
        pod 'FFBaseLabelCustomTest',:path => '/Users/derrick/Desktop/pod组建验证/FFBaseLabel'
	pod 'CTMediator'
  # Pods for CustomLabel

end
